In this notebook, we are going to cover some of the most fundamental concepts of tensors using tensorflow

More specifically, we are going to cover: 
1. Introduction to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors & NumPy
5. Using @tf.function (a way to speed up regular python functions)
6. Using GPUs with Tensorflow (or TPUs)
7. Exercises


## Introduction to Tensors

In [3]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of the vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the dimension of the matrix
matrix.ndim

2

In [8]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.], [3., 6.], [5., 2.]],  dtype=tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [ 5.,  2.]], dtype=float16)>

In [9]:
# Check the dimension of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have created so far: 

1. Scalar: a single number
2. Vector: a number with direction
3. Matrix: a 2-dimensional array of numbers
4. Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with tf.variable

In [12]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in the changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Let's try change for unchangeable tensor 
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating Random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [17]:
# Createa two random tensors 
random_1 = tf.random.Generator.from_seed(7) #set seed for reproducibility
random_1 =  random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# Are they equal
random_1,  random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [18]:
# shuffle a tensor - valuable for when you want to shuffle your data so the inherent order doesn't effect learning
not_shuffled = tf.constant([[10,7], [3,4], [2,5]])

not_shuffled.ndim

# shuffle our non-shuffled tensor 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed

> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence. 

### Other ways to make tensors

In [21]:
# create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors 

The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [23]:
# NumPy arrays into tensors 
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [25]:
numpy_B = np.arange(1,33, dtype=np.int32)
numpy_B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype=int32)

In [26]:
B = tf.constant(numpy_B, shape=(2, 4,2, 2))
B

<tf.Tensor: shape=(2, 4, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28]],

        [[29, 30],
         [31, 32]]]], dtype=int32)>

In [27]:
B.ndim

4

### Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes: 

* Shape
* Axis/Dimension
* Size
* Rank

In [28]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# getting shape, dimension, size
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
# get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like python lists

In [31]:
# get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# create a rank 2 tensor (2 Dimensions)
rank_2_tensor = tf.constant([[10,7], [3,4]])
rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [34]:
# get the last item of each of our rank 2 tensor 
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [35]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
# expand zero axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensor (Tensor operations)

**Basic Operations**

`+`, `-`, `*`, `/`

In [40]:
# Adding values to a tensor using the addition operator 
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

# Original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [41]:
# Multiplication 
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [42]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [43]:
# we can use the tensorflow built-in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

**Matrix Multiplication**

In Machine learning, matrix multiplication is one of the most common tensor operation

In [45]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
# create a tensor (3,2) tensor
X = tf.constant([[1, 2], [3, 4], [5, 6]])
Y = tf.constant([[7, 8], [9,10], [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [53]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

**Dot Product**

Matrix multiplication is also referred to as the dot product

We can perform matrix multiplication using: 

* `tf.matmul()`
* `tf.tensordot()`

In [57]:
# perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [58]:
# perform matrix multiplication between X and Y (tranposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [59]:
# perform matrix multiplication vetween X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

> **Note**: Generally when performing matrix multiplication on two tensors and one of the axes does not line up, you will tranpose (rather reshape) one of the tensors to get satisfy the matrix multiplication rules

In [63]:
# Create aa new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [64]:
C = tf.constant([3, 4])
C.dtype

tf.int32

In [65]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [67]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 4.], dtype=float16)>,
 tf.float16)

### Aggregating Tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [68]:
# Get the absolute values 
D = tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Let's go through the following forms of aggregation: 
* Get maximum
* Get minimum
* Get mean of a tensor
* Get the sum of a tensor

In [70]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=70))
E

<tf.Tensor: shape=(70,), dtype=int64, numpy=
array([ 0, 42, 19, 72, 43, 70, 25, 41, 16, 50, 55, 68, 17, 14, 22, 83, 72,
       15,  9, 19, 22, 84, 58, 62, 59, 86, 44, 72, 44, 70, 72, 99,  6,  2,
       15, 77, 66,  3, 62, 79, 11, 25, 98,  1, 24, 18, 98, 12, 86, 61, 81,
       38, 78, 20,  8, 19, 21, 21,  6, 85, 97, 75, 20, 70, 67, 73, 47,  7,
       96, 48])>

In [71]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=70>, TensorShape([70]), 1)

In [73]:
# find minimium
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [74]:
# find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [75]:
# fine mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [77]:
# find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3245>

In [94]:
# find variance 

# to find variance we need access to tensorflow_probablity

import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=919>

In [96]:
# find std
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.322569>

In [97]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=919.4581>

### Find positional Maximum and Minimum

In [98]:
# create a new tensor for finding positional minimuma and maximum
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [99]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [100]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [101]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [102]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [104]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [105]:
# Index on our smallest value position
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (remove all single dimensions)

In [108]:
# create a tensor to get started 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [109]:
G.shape

TensorShape([1, 1, 1, 50])

In [111]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding

In [112]:
# create a list of indices 
some_list = [0, 1 , 2, 3] # could be red, green, blue, purple
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, Log and Square root

In [113]:
# create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [114]:
# Square 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [115]:
# Square-root
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [121]:
# Log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensorflow reacts beautifully with NumPy arrays

> **Note**: One of the main difference between tensorlfow tensor and Numpy array is that a Tf Tensor can run on a GPU or TPU (for faster numerical processing)

In [122]:
# create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [123]:
# convert the tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [125]:
# convert tensor J to NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [127]:
# the deafault types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [5]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

> **Note:** if you have access to a CUDA-enabled GPU, TF will automatically use it whenever possible

In [7]:
!nvidia-smi

Thu Sep  8 09:06:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Exercises

In [9]:
# 1
scalar = tf.constant(5)


vector = tf.constant([10,10])


matrix = tf.constant([[10,7], [7, 10]])

scalar, vector, matrix



(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>)

In [13]:
# 2
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [14]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [15]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [20]:
# 3
ten1 = tf.random.uniform(shape=[5, 300], minval=0., maxval=1.)
ten2 = tf.random.uniform(shape=[5, 300], minval=0., maxval=1.)
ten1, ten2


(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.65936685, 0.9784359 , 0.56297374, ..., 0.25520337, 0.12454569,
         0.4158963 ],
        [0.03747749, 0.8172039 , 0.22549188, ..., 0.10162389, 0.20264661,
         0.23031008],
        [0.77367485, 0.65083694, 0.8419517 , ..., 0.71324635, 0.45776892,
         0.10562825],
        [0.5363257 , 0.66343474, 0.70956576, ..., 0.8589786 , 0.76285505,
         0.13548887],
        [0.48342204, 0.94610596, 0.11576056, ..., 0.31313145, 0.54039955,
         0.5582558 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6848608 , 0.18047214, 0.14935327, ..., 0.5173409 , 0.46271896,
         0.14463091],
        [0.03755367, 0.32789886, 0.70343995, ..., 0.91369724, 0.47049522,
         0.66544306],
        [0.43088043, 0.11627197, 0.51131   , ..., 0.9068959 , 0.38364828,
         0.95948386],
        [0.43608177, 0.27610087, 0.720585  , ..., 0.5271467 , 0.66258097,
         0.6161183 ],
        [0.22677

In [22]:
# 4
tf.matmul(ten1, tf.transpose(ten2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.010315, 75.06272 , 71.488266, 76.931595, 74.72931 ],
       [70.99964 , 75.08721 , 71.27653 , 77.365616, 73.017975],
       [70.11439 , 74.90633 , 68.35725 , 73.36237 , 70.63983 ],
       [72.37962 , 80.305786, 72.42446 , 77.23573 , 77.978264],
       [70.84554 , 76.7114  , 69.645935, 78.05246 , 73.888084]],
      dtype=float32)>

In [25]:
# 5
tf.tensordot(ten1, tf.transpose(ten2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.010315, 75.06272 , 71.488266, 76.931595, 74.72931 ],
       [70.99964 , 75.08721 , 71.27653 , 77.365616, 73.017975],
       [70.11439 , 74.90633 , 68.35725 , 73.36237 , 70.63983 ],
       [72.37962 , 80.305786, 72.42446 , 77.23573 , 77.978264],
       [70.84554 , 76.7114  , 69.645935, 78.05246 , 73.888084]],
      dtype=float32)>

In [30]:
# 6
ten3 = tf.random.uniform(shape=[224, 224, 3], minval=0., maxval=1.)
ten3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[1.1599004e-01, 5.4082978e-01, 9.9408352e-01],
        [3.3839703e-01, 2.2382307e-01, 7.9768133e-01],
        [9.9396706e-04, 7.1201324e-01, 9.2403913e-01],
        ...,
        [7.4340904e-01, 2.9239416e-01, 9.7178888e-01],
        [6.9633782e-01, 1.4775991e-03, 2.5033355e-01],
        [9.6878815e-01, 3.3849335e-01, 1.9859338e-01]],

       [[7.6056898e-01, 6.3992786e-01, 6.7459118e-01],
        [6.5945184e-01, 2.7806163e-01, 7.2224486e-01],
        [3.1142306e-01, 4.2284596e-01, 1.3693357e-01],
        ...,
        [8.0189109e-02, 6.2971997e-01, 2.7144921e-01],
        [2.4588633e-01, 1.5902829e-01, 7.8307378e-01],
        [1.1798239e-01, 8.1993759e-01, 1.2064147e-01]],

       [[1.7265558e-02, 2.7964532e-01, 2.6240349e-03],
        [4.4654191e-01, 2.2262371e-01, 1.2202299e-01],
        [4.4191587e-01, 9.7927177e-01, 3.8569212e-01],
        ...,
        [2.6134837e-01, 4.4273210e-01, 5.4342961e-01],
        [4.5482218e-01

In [34]:
# 7
tf.reduce_max(ten3), tf.reduce_min(ten3)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9999981>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.7775764e-05>)

In [39]:
# 8
ten4 = tf.random.uniform(shape=[1, 224, 224, 3])

tf.squeeze(ten4).shape, ten4.shape

(TensorShape([224, 224, 3]), TensorShape([1, 224, 224, 3]))

In [41]:
# 9
ten5 = tf.constant([2, 3, 11, 9, 10])

tf.argmax(ten5)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [43]:
# 10
tf.one_hot(ten5, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>